# Generated by Django 4.2.5 on 2023-10-07 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postLikes',
            field=models.ManyToManyField(related_name='liked_posts', through='network.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
