# Generated by Django 4.2.5 on 2023-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_post_postlikes_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
